CREATE TABLE TIPO_PLANTA (
    TIPO_PLANTA_ID SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE PLANTA (
    PLANTA_ID SERIAL PRIMARY KEY NOT NULL,
    TIPO_PLANTA_ID INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    UMIDADE_SOLO_IDEAL DECIMAL(5,2) NOT NULL DEFAULT 0,
    TEMPERATURA_SOLO_IDEAL DECIMAL(5,2) NOT NULL DEFAULT 0,
    FOREIGN KEY (TIPO_PLANTA_ID) REFERENCES TIPO_PLANTA(TIPO_PLANTA_ID)
);

CREATE TABLE MODULO (
    MODULO_ID SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE MODULO_PLANTA (
    MODULO_ID INTEGER REFERENCES MODULO(MODULO_ID),
    PLANTA_ID INTEGER REFERENCES PLANTA(PLANTA_ID),
    UNIQUE (MODULO_ID, PLANTA_ID)
);

CREATE TABLE TIPO_USUARIO (
    TIPO_USUARIO_ID SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE USUARIO (
    USUARIO_ID SERIAL PRIMARY KEY NOT NULL,
    TIPO_USUARIO_ID INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(320) NOT NULL UNIQUE,
    SENHA VARCHAR(60) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (TIPO_USUARIO_ID) REFERENCES TIPO_USUARIO(TIPO_USUARIO_ID)
);

CREATE TABLE KIT (
    KIT_ID SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255),
    DATA_ULTIMO_USO TIMESTAMP NULL
);

CREATE TABLE KIT_USUARIO (
    KIT_ID INTEGER REFERENCES KIT(KIT_ID),
    USUARIO_ID INTEGER REFERENCES USUARIO(USUARIO_ID),
    UNIQUE (KIT_ID, USUARIO_ID)
);