CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251024001612_InitialCreate', '9.0.10');

CREATE TABLE "PlantSpecs" (
    "Id" uuid NOT NULL,
    "CommonName" text,
    "ScientificName" text,
    "Type" integer NOT NULL,
    "IdealTempMin" double precision NOT NULL,
    "IdealTempMax" double precision NOT NULL,
    "Light" text,
    "WateringFrequency" text,
    "Notes" text,
    "IdealMoistureMin" double precision NOT NULL,
    "IdealMoistureMax" double precision NOT NULL,
    CONSTRAINT "PK_PlantSpecs" PRIMARY KEY ("Id")
);

CREATE TABLE "SmartPots" (
    "Id" uuid NOT NULL,
    "QrCode" text,
    "Location" text,
    "ConnectionStatus" boolean NOT NULL,
    "ReservoirLevel" double precision NOT NULL,
    "LastSoilMoisture" double precision NOT NULL,
    "LastIrrigation" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SmartPots" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "PasswordHash" text,
    "EmailConfirmed" boolean,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "IrrigationHistories" (
    "Id" uuid NOT NULL,
    "SmartPotId" uuid NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "WaterAmount" double precision NOT NULL,
    "MoistureBefore" double precision NOT NULL,
    "MoistureAfter" double precision NOT NULL,
    CONSTRAINT "PK_IrrigationHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IrrigationHistories_SmartPots_SmartPotId" FOREIGN KEY ("SmartPotId") REFERENCES "SmartPots" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Plants" (
    "Id" uuid NOT NULL,
    "Name" text,
    "RegistrationDate" timestamp with time zone NOT NULL,
    "SmartPotId" uuid NOT NULL,
    "PlantSpecificationId" uuid NOT NULL,
    CONSTRAINT "PK_Plants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Plants_PlantSpecs_PlantSpecificationId" FOREIGN KEY ("PlantSpecificationId") REFERENCES "PlantSpecs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Plants_SmartPots_SmartPotId" FOREIGN KEY ("SmartPotId") REFERENCES "SmartPots" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserNotifications" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "IsRead" boolean NOT NULL,
    "Title" text,
    "Message" text,
    "Type" integer NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_UserNotifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserNotifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_IrrigationHistories_SmartPotId" ON "IrrigationHistories" ("SmartPotId");

CREATE INDEX "IX_Plants_PlantSpecificationId" ON "Plants" ("PlantSpecificationId");

CREATE INDEX "IX_Plants_SmartPotId" ON "Plants" ("SmartPotId");

CREATE INDEX "IX_UserNotifications_UserId" ON "UserNotifications" ("UserId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251028165018_AddEntities', '9.0.10');

ALTER TABLE "IrrigationHistories" DROP CONSTRAINT "FK_IrrigationHistories_SmartPots_SmartPotId";

ALTER TABLE "Plants" DROP CONSTRAINT "FK_Plants_PlantSpecs_PlantSpecificationId";

ALTER TABLE "Plants" DROP CONSTRAINT "FK_Plants_SmartPots_SmartPotId";

ALTER TABLE "UserNotifications" DROP CONSTRAINT "FK_UserNotifications_Users_UserId";

DROP TABLE "PlantSpecs";

ALTER TABLE "Users" DROP CONSTRAINT "PK_Users";

ALTER TABLE "Plants" DROP CONSTRAINT "PK_Plants";

ALTER TABLE "UserNotifications" DROP CONSTRAINT "PK_UserNotifications";

ALTER TABLE "SmartPots" DROP CONSTRAINT "PK_SmartPots";

ALTER TABLE "IrrigationHistories" DROP CONSTRAINT "PK_IrrigationHistories";

ALTER TABLE "Users" RENAME TO "USERS";

ALTER TABLE "Plants" RENAME TO "PLANTS";

ALTER TABLE "UserNotifications" RENAME TO "USER_NOTIFICATIONS";

ALTER TABLE "SmartPots" RENAME TO "SMART_POTS";

ALTER TABLE "IrrigationHistories" RENAME TO "IRRIGATION_HISTORIES";

ALTER TABLE "USERS" RENAME COLUMN "Name" TO "NAME";

ALTER TABLE "USERS" RENAME COLUMN "Email" TO "EMAIL";

ALTER TABLE "USERS" RENAME COLUMN "PasswordHash" TO "PASSWORD_HASH";

ALTER TABLE "USERS" RENAME COLUMN "EmailConfirmed" TO "EMAIL_CONFIRMED";

ALTER TABLE "USERS" RENAME COLUMN "Id" TO "USER_ID";

ALTER INDEX "IX_Users_Email" RENAME TO "IX_USERS_EMAIL";

ALTER TABLE "PLANTS" RENAME COLUMN "Name" TO "NAME";

ALTER TABLE "PLANTS" RENAME COLUMN "SmartPotId" TO "SMART_POT_ID";

ALTER TABLE "PLANTS" RENAME COLUMN "RegistrationDate" TO "REGISTRATION_DATE";

ALTER TABLE "PLANTS" RENAME COLUMN "PlantSpecificationId" TO "PLANT_SPECIFICATION_ID";

ALTER TABLE "PLANTS" RENAME COLUMN "Id" TO "PLANT_ID";

ALTER INDEX "IX_Plants_SmartPotId" RENAME TO "IX_PLANTS_SMART_POT_ID";

ALTER INDEX "IX_Plants_PlantSpecificationId" RENAME TO "IX_PLANTS_PLANT_SPECIFICATION_ID";

ALTER TABLE "USER_NOTIFICATIONS" RENAME COLUMN "Type" TO "TYPE";

ALTER TABLE "USER_NOTIFICATIONS" RENAME COLUMN "Title" TO "TITLE";

ALTER TABLE "USER_NOTIFICATIONS" RENAME COLUMN "Status" TO "STATUS";

ALTER TABLE "USER_NOTIFICATIONS" RENAME COLUMN "Message" TO "MESSAGE";

ALTER TABLE "USER_NOTIFICATIONS" RENAME COLUMN "UserId" TO "USER_ID";

ALTER TABLE "USER_NOTIFICATIONS" RENAME COLUMN "SentAt" TO "SENT_AT";

ALTER TABLE "USER_NOTIFICATIONS" RENAME COLUMN "IsRead" TO "IS_READ";

ALTER TABLE "USER_NOTIFICATIONS" RENAME COLUMN "Id" TO "USER_NOTIFICATION_ID";

ALTER INDEX "IX_UserNotifications_UserId" RENAME TO "IX_USER_NOTIFICATIONS_USER_ID";

ALTER TABLE "SMART_POTS" RENAME COLUMN "Location" TO "LOCATION";

ALTER TABLE "SMART_POTS" RENAME COLUMN "ReservoirLevel" TO "RESERVOIR_LEVEL";

ALTER TABLE "SMART_POTS" RENAME COLUMN "QrCode" TO "QR_CODE";

ALTER TABLE "SMART_POTS" RENAME COLUMN "LastSoilMoisture" TO "LAST_SOIL_MOISTURE";

ALTER TABLE "SMART_POTS" RENAME COLUMN "LastIrrigation" TO "LAST_IRRIGATION";

ALTER TABLE "SMART_POTS" RENAME COLUMN "ConnectionStatus" TO "CONNECTION_STATUS";

ALTER TABLE "SMART_POTS" RENAME COLUMN "Id" TO "SMART_POT_ID";

ALTER TABLE "IRRIGATION_HISTORIES" RENAME COLUMN "Timestamp" TO "TIMESTAMP";

ALTER TABLE "IRRIGATION_HISTORIES" RENAME COLUMN "WaterAmount" TO "WATER_AMOUNT";

ALTER TABLE "IRRIGATION_HISTORIES" RENAME COLUMN "SmartPotId" TO "SMART_POT_ID";

ALTER TABLE "IRRIGATION_HISTORIES" RENAME COLUMN "MoistureBefore" TO "MOISTURE_BEFORE";

ALTER TABLE "IRRIGATION_HISTORIES" RENAME COLUMN "MoistureAfter" TO "MOISTURE_AFTER";

ALTER TABLE "IRRIGATION_HISTORIES" RENAME COLUMN "Id" TO "IRRIGATION_HISTORY_ID";

ALTER INDEX "IX_IrrigationHistories_SmartPotId" RENAME TO "IX_IRRIGATION_HISTORIES_SMART_POT_ID";

ALTER TABLE "USERS" ALTER COLUMN "NAME" TYPE character varying(200);

ALTER TABLE "USERS" ALTER COLUMN "EMAIL" TYPE character varying(255);

UPDATE "USERS" SET "PASSWORD_HASH" = '' WHERE "PASSWORD_HASH" IS NULL;
ALTER TABLE "USERS" ALTER COLUMN "PASSWORD_HASH" SET NOT NULL;
ALTER TABLE "USERS" ALTER COLUMN "PASSWORD_HASH" SET DEFAULT '';

UPDATE "USERS" SET "EMAIL_CONFIRMED" = FALSE WHERE "EMAIL_CONFIRMED" IS NULL;
ALTER TABLE "USERS" ALTER COLUMN "EMAIL_CONFIRMED" SET NOT NULL;
ALTER TABLE "USERS" ALTER COLUMN "EMAIL_CONFIRMED" SET DEFAULT FALSE;

ALTER TABLE "USERS" ADD "CREATED_AT" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "USERS" ADD "UPDATED_AT" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "PLANTS" ALTER COLUMN "NAME" TYPE character varying(120);
UPDATE "PLANTS" SET "NAME" = '' WHERE "NAME" IS NULL;
ALTER TABLE "PLANTS" ALTER COLUMN "NAME" SET NOT NULL;
ALTER TABLE "PLANTS" ALTER COLUMN "NAME" SET DEFAULT '';

ALTER TABLE "PLANTS" ADD "CREATED_AT" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "PLANTS" ADD "UPDATED_AT" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "USER_NOTIFICATIONS" ALTER COLUMN "TITLE" TYPE character varying(150);
UPDATE "USER_NOTIFICATIONS" SET "TITLE" = '' WHERE "TITLE" IS NULL;
ALTER TABLE "USER_NOTIFICATIONS" ALTER COLUMN "TITLE" SET NOT NULL;
ALTER TABLE "USER_NOTIFICATIONS" ALTER COLUMN "TITLE" SET DEFAULT '';

ALTER TABLE "USER_NOTIFICATIONS" ALTER COLUMN "MESSAGE" TYPE character varying(500);
UPDATE "USER_NOTIFICATIONS" SET "MESSAGE" = '' WHERE "MESSAGE" IS NULL;
ALTER TABLE "USER_NOTIFICATIONS" ALTER COLUMN "MESSAGE" SET NOT NULL;
ALTER TABLE "USER_NOTIFICATIONS" ALTER COLUMN "MESSAGE" SET DEFAULT '';

ALTER TABLE "USER_NOTIFICATIONS" ADD "CREATED_AT" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "USER_NOTIFICATIONS" ADD "UPDATED_AT" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "SMART_POTS" ALTER COLUMN "LOCATION" TYPE character varying(120);
UPDATE "SMART_POTS" SET "LOCATION" = '' WHERE "LOCATION" IS NULL;
ALTER TABLE "SMART_POTS" ALTER COLUMN "LOCATION" SET NOT NULL;
ALTER TABLE "SMART_POTS" ALTER COLUMN "LOCATION" SET DEFAULT '';

UPDATE "SMART_POTS" SET "QR_CODE" = '' WHERE "QR_CODE" IS NULL;
ALTER TABLE "SMART_POTS" ALTER COLUMN "QR_CODE" SET NOT NULL;
ALTER TABLE "SMART_POTS" ALTER COLUMN "QR_CODE" SET DEFAULT '';

ALTER TABLE "SMART_POTS" ADD "CREATED_AT" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "SMART_POTS" ADD "UPDATED_AT" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "IRRIGATION_HISTORIES" ADD "CREATED_AT" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "IRRIGATION_HISTORIES" ADD "UPDATED_AT" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("USER_ID");

ALTER TABLE "PLANTS" ADD CONSTRAINT "PK_PLANTS" PRIMARY KEY ("PLANT_ID");

ALTER TABLE "USER_NOTIFICATIONS" ADD CONSTRAINT "PK_USER_NOTIFICATIONS" PRIMARY KEY ("USER_NOTIFICATION_ID");

ALTER TABLE "SMART_POTS" ADD CONSTRAINT "PK_SMART_POTS" PRIMARY KEY ("SMART_POT_ID");

ALTER TABLE "IRRIGATION_HISTORIES" ADD CONSTRAINT "PK_IRRIGATION_HISTORIES" PRIMARY KEY ("IRRIGATION_HISTORY_ID");

CREATE TABLE "PLANT_SPECS" (
    "PLANT_SPECIFICATION_ID" uuid NOT NULL,
    "COMMON_NAME" character varying(100) NOT NULL,
    "SCIENTIFIC_NAME" character varying(100) NOT NULL,
    "TYPE" integer NOT NULL,
    "IDEAL_TEMP_MIN" double precision NOT NULL,
    "IDEAL_TEMP_MAX" double precision NOT NULL,
    "LIGHT" character varying(100) NOT NULL,
    "WATERING_FREQUENCY" text NOT NULL,
    "NOTES" character varying(500) NOT NULL,
    "IDEAL_MOISTURE_MIN" double precision NOT NULL,
    "IDEAL_MOISTURE_MAX" double precision NOT NULL,
    "CREATED_AT" timestamp with time zone NOT NULL,
    "UPDATED_AT" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PLANT_SPECS" PRIMARY KEY ("PLANT_SPECIFICATION_ID")
);

CREATE UNIQUE INDEX "IX_SMART_POTS_QR_CODE" ON "SMART_POTS" ("QR_CODE");

ALTER TABLE "IRRIGATION_HISTORIES" ADD CONSTRAINT "FK_IRRIGATION_HISTORIES_SMART_POTS_SMART_POT_ID" FOREIGN KEY ("SMART_POT_ID") REFERENCES "SMART_POTS" ("SMART_POT_ID") ON DELETE CASCADE;

ALTER TABLE "PLANTS" ADD CONSTRAINT "FK_PLANTS_PLANT_SPECS_PLANT_SPECIFICATION_ID" FOREIGN KEY ("PLANT_SPECIFICATION_ID") REFERENCES "PLANT_SPECS" ("PLANT_SPECIFICATION_ID") ON DELETE CASCADE;

ALTER TABLE "PLANTS" ADD CONSTRAINT "FK_PLANTS_SMART_POTS_SMART_POT_ID" FOREIGN KEY ("SMART_POT_ID") REFERENCES "SMART_POTS" ("SMART_POT_ID") ON DELETE CASCADE;

ALTER TABLE "USER_NOTIFICATIONS" ADD CONSTRAINT "FK_USER_NOTIFICATIONS_USERS_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID") ON DELETE CASCADE; 

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251031005316_ReestruturandoBancoDeDados', '9.0.10');

COMMIT;